In [23]:
import pandas as pd


df = pd.read_json('data/bloomberg_quint_news.json')

print(df.head())

                                                 url  \
0  https://www.bloombergquint.com/markets/all-you...
1  https://www.bloombergquint.com/business/bridge...
2  https://www.bloombergquint.com/markets/stocks-...
3  https://www.bloombergquint.com/research-report...
4  https://www.bloombergquint.com/business/cp-rai...

                                               title  \
0  All You Need To Know Going Into Trade On Septe...
1  Bridgestone CEO Backs Safe Tokyo Olympics, Dia...
2  Stocks To Watch: HCL Tech, Cyient, M&M Financi...
3  Localised Lockdowns Cannot But Impinge On Econ...
4  CP Rail Wins Regulator Exemption From Tougher ...

                                   short_description  \
0  Stocks in the news, big brokerage calls of the...
1  Bridgestone CEO Backs Safe Tokyo Olympics, Dia...
2     Here are the stocks to watch in trade today...
3  Localised Lockdowns Cannot But Impinge On Econ...
4  CP Rail Wins Regulator Exemption From Tougher ...

                               author              date_created  \
0                    Darshan A Nakhwa  23 Sep 2021, 7:05 AM IST
1                    Shiho Takezawa &  23 Apr 2021, 5:35 AM IST
2                             BQ Desk  23 Apr 2021, 7:29 AM IST
3  Nirmal Bang Institutional Research  26 Apr 2021, 7:58 AM IST
4                        Thomas Black  24 Apr 2021, 7:08 AM IST

              date_modified          category  \
0  23 Sep 2021, 7:05 AM IST           Markets
1  23 Apr 2021, 6:35 AM IST          Business
2  23 Apr 2021, 7:29 AM IST           Markets
3  26 Apr 2021, 7:58 AM IST  Research Reports
4  24 Apr 2021, 7:44 AM IST          Business

                                     raw_description  \
0  <div class="story-element story-element-text">...
1  <div class="story-element story-element-text">...
2  <div class="story-element story-element-text">...
3  <div class="story-element story-element-text">...
4  <div class="story-element story-element-text">...

                                         description  \
0  Asian stocks were steady early Thursday after ...
1   Bridgestone Corp. will support the Tokyo Olym...
2  Indian equity benchmarks reversed losses made ...
3  Nirmal Bang Report, We assess the ‘state of af...
4   Canadian Pacific Railway Ltd. won a petition ...

                         publisher          scraped_at
0  https://www.bloombergquint.com/ 2021-09-24 00:01:25
1  https://www.bloombergquint.com/ 2021-09-24 00:01:26
2  https://www.bloombergquint.com/ 2021-09-24 00:01:26
3  https://www.bloombergquint.com/ 2021-09-24 00:01:26
4  https://www.bloombergquint.com/ 2021-09-24 00:01:27

In [24]:
def check_missing_values(df):
    # Check for NaN, missing, or NaT values
    missing_rows = df[df.isnull().any(axis=1)]

    if not missing_rows.empty:
        print("Deleting rows with missing values...")
        df.dropna(inplace=True)
        print("Rows with missing values have been deleted.")
    else:
        print("There are no missing values in the DataFrame.")

# Example usage:
check_missing_values(df)

Deleting rows with missing values...
Rows with missing values have been deleted.

In [25]:
from datetime import datetime
import pandas as pd

def filter_by_recent_date(df, filter_by_recent=True):
    # Remove 'IST' from date strings
    df['date_created'] = df['date_created'].str.replace(' IST', '')
    df['date_modified'] = df['date_modified'].str.replace(' IST', '')

    # Convert date strings to datetime objects
    df['date_created'] = pd.to_datetime(df['date_created'], format='%d %b %Y, %I:%M %p')
    df['date_modified'] = pd.to_datetime(df['date_modified'], format='%d %b %Y, %I:%M %p')

    if filter_by_recent:
        # Find the most recent date
        most_recent_date = max(df['date_created'].max(), df['date_modified'].max())

        # Filter the DataFrame based on the most recent date
        filtered_df = df[(df['date_created'] == most_recent_date) | (df['date_modified'] == most_recent_date)]
    else:
        filtered_df = df  # If filter_by_recent is False, return the original DataFrame
    
    return filtered_df


filter_by_recent_date(df, filter_by_recent=True)

,url,title,short_description,author,date_created,date_modified,category,raw_description,description,publisher,scraped_at
4104,https://www.bloombergquint.com/politics/schume...,Schumer Says Democrats Have ‘Framework’ to Pay...,Schumer Says Democrats Have ‘Framework’ to Pay...,Billy House &,2021-09-23 20:37:00,2021-09-24 00:10:00,Politics,"<div class=""story-element story-element-text"">...",Senate Majority Leader Chuck Schumer said the...,https://www.bloombergquint.com/,2021-09-24 00:18:49